# just to make PodWeaver happy atm
package Sub::Spec::Manual::Spec;
# ABSTRACT: Spec for sub spec


1;

__END__
=pod

=head1 NAME

Sub::Spec::Manual::Spec - Spec for sub spec

=head1 VERSION

version 0.13

=head1 DESCRIPTION

This documentation specifies the syntax for sub spec.

=head2 CLAUSE

=head2 Properties

=over 4

=item * per_import => BOOL

If true, this means that for each importer, Sub::Spec will construct a new
wrapper for the subroutine.

Retry and timeout are two such clauses.

=item * per_call => BOOL

If true, this means that in each subroutine call you can pass some value to
modify the clause behaviour: -CLAUSENAME => VALUE. The wrapper is able to act
upon the different clause arguments.

Retry and timeout are two such clauses. You can specify retry and timeout on a
per-call basis:

 search_files(root => '/', pattern => qr/^[abc]/, -timeout => 30);
 download_url(url => 'http://host/path', -timeout => 300, -retry => 4);

=back

=head1 ADDING NEW CLAUSE

=head1 SEE ALSO

XXX

=head1 AUTHOR

Steven Haryanto <stevenharyanto@gmail.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2011 by Steven Haryanto.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut

